name: Nightly Staging
on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: false

jobs:
  verify_environment:
    name: Verify Environment
    uses: ./.github/workflows/reusable-verify-environment.yaml
    secrets: inherit
