name: Nightly Staging
on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

concurrency:
  group: staging
  cancel-in-progress: false

jobs:
  verify_environment:
    name: Verify Environment
    uses: ./.github/workflows/reusable-verify-environment.yaml
    secrets: inherit
    with:
      environment: staging

  build:
    name: Build
    uses: ./.github/workflows/reusable-build.yaml
    secrets: inherit
    with:
      environment: staging

  deploy:
    name: Deploy
    needs: build
    uses: ./.github/workflows/reusable-deploy.yaml
    secrets: inherit
    with:
      environment: staging

  playwright:
    name: Playwright
    needs: deploy
    uses: ./.github/workflows/reusable-playwright.yaml
    secrets: inherit
    with:
      url: ${{ needs.deploy.outputs.url }}
      environment: staging
