name: CI
on:
  pull_request:
    branches: [main]
    types: [opened, reopened, synchronize, ready_for_review]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  verify:
    name: Test ${{ matrix.app }} ${{ matrix.release }}
    runs-on: ubuntu-latest

    steps:
      - name: Clone repository
        uses: actions/checkout@v4

      - name: Dump secrets
        run: echo $SECRET
        env:
          SECRET: ${{ secrets.TEST }}
