name: Verify Environment
on:
  workflow_call:
    inputs:
      environment:
        description: "The environment to run in"
        required: true
        type: string

jobs:
   verify_environment:
    name: Test ${{ matrix.app }} ${{ matrix.release }}
    runs-on: ubuntu-latest
    timeout-minutes: 30
    environment: ${{ inputs.environment }}
    strategy:
      fail-fast: false
      matrix:
        release: [ethereum.sulu, polygon.sulu]

    steps:
      - name: Clone repository
        uses: actions/checkout@v4

      - name: Install dependencies
        uses: ./.github/actions/install-dependencies
        with:
          github-token: ${{ github.token }}

      - name: Run tests
        run: pnpm run --filter @enzymefinance/environment test
        env:
          ALCHEMY_API_KEY: ${{ secrets.ALCHEMY_API_KEY }}
          RELEASE: ${{ matrix.release }}
          COINGECKO_MINUTE_RATE: 5 # low max rate (per app per shard)
