name: Verify
on:
  workflow_call:

jobs:
  linting:
    name: Linting
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - name: Clone repository
        uses: actions/checkout@v4

      - name: Install dependencies
        uses: ./.github/actions/install-dependencies

      - name: Check linting
        run: pnpm run lint

  types:
    name: Types
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - name: Clone repository
        uses: actions/checkout@v4

      - name: Install dependencies
        uses: ./.github/actions/install-dependencies

      - name: Run build
        run: pnpm run build

      - name: Check types
        run: pnpm run typecheck

  build:
    name: Build
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - name: Clone repository
        uses: actions/checkout@v4

      - name: Install dependencies
        uses: ./.github/actions/install-dependencies

      - name: Run build
        run: pnpm run build

  test:
    name: Test (${{ matrix.shard }})
    runs-on: ubuntu-latest
    timeout-minutes: 10
    strategy:
      fail-fast: true
      matrix:
        shard: [1/4, 2/4, 3/4, 4/4]

    steps:
      - name: Clone repository
        uses: actions/checkout@v4

      - name: Install foundry
        uses: foundry-rs/foundry-toolchain@v1
        with:
          version: nightly

      - name: Install dependencies
        uses: ./.github/actions/install-dependencies

      - name: Run tests
        working-directory: packages/sdk
        run: pnpm run test --shard ${{ matrix.shard }}
        env:
          VITE_ANVIL_FORK_URL: ${{ secrets.VITE_ANVIL_FORK_URL }}
          VITE_ANVIL_FORK_BLOCK_NUMBER: ${{ secrets.VITE_ANVIL_FORK_BLOCK_NUMBER }}
          VITE_ANVIL_FORK_URL_POLYGON: ${{ secrets.VITE_ANVIL_FORK_URL_POLYGON }}
          VITE_ANVIL_FORK_BLOCK_NUMBER_POLYGON: ${{ secrets.VITE_ANVIL_FORK_BLOCK_NUMBER_POLYGON }}

  size:
    name: Size
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - name: Clone repository
        uses: actions/checkout@v4

      - name: Install dependencies
        uses: ./.github/actions/install-dependencies

      - name: Report build size
        uses: preactjs/compressed-size-action@v2
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
