name: Manual Verify Environment
on: workflow_dispatch

permissions: {}

jobs:
  verify_environment:
    name: Verify Environment
    uses: ./.github/workflows/reusable-verify-environment.yaml
    secrets: inherit
